export const API_URL = 'http://localhost:3000';

export const APP_CONFIG = {
  APP_NAME: 'Mobile Banking',
  VERSION: '1.0.0',
  CURRENCY: 'USD',
  DATE_FORMAT: 'YYYY-MM-DD',
  DATETIME_FORMAT: 'YYYY-MM-DD HH:mm:ss',
  MINIMUM_PASSWORD_LENGTH: 8,
  SESSION_TIMEOUT: 30 * 60 * 1000, // 30 minutes
  TRANSACTION_TYPES: {
    TRANSFER: 'TRANSFER',
    DEPOSIT: 'DEPOSIT',
    WITHDRAWAL: 'WITHDRAWAL',
    BILL_PAYMENT: 'BILL_PAYMENT',
    CHECK_DEPOSIT: 'CHECK_DEPOSIT',
  },
  ACCOUNT_TYPES: {
    SAVINGS: 'SAVINGS',
    CHECKING: 'CHECKING',
    INVESTMENT: 'INVESTMENT',
    CREDIT: 'CREDIT',
  },
}; 